services:
  web:
    image: site-frankenphp
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app/
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./store/:/app/store/
      # - /Users/rw/dev/slowhand/:/app/cms/
      # - /Users/rw/dev/pickel/:/app/pickel/
    environment:
      - SLOWHAND_VAR=/app/store
      - SLOWHAND_PROJECTS=/app/projects
      - SLOWHAND_ADMIN_SECRET=123456
      - SLFT_BUILD_KEY=1234
    ports:
      - 9901:8001
      - 9902:8002
      - 9903:1199
  #install:
  #  image: wolfi-php
  #  volumes:
  #    - ./:/app
  #  restart: no
  #  entrypoint: ["sh"]
